# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='inTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='outTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
