# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20160629_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
