# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20160629_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together=set([('employee', 'date')]),
        ),
    ]
