# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20160629_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='modifyToken',
            field=models.CharField(default='alskdjfalkdsjf', max_length=64),
            preserve_default=False,
        ),
    ]
