# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_dailyattendance_modifytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='modifyToken',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
